### ISSUE TITLE
Change the colortheme

### ISSUE THREAD

**Issue by Hamzakam** [Hamzakam/StackGUI#1]
Change the color theme to be something more pleasing to the eye and improve UX.

**Comment by AangTheLast** [comment]
I Would Like to Accept This Request

**Comment by Hamzakam** [comment]
Okay @AangTheLast. I will assign you this request.

**Comment by OmkarGeedh** [comment]
I would like to work on it

**Comment by Hamzakam** [comment]
Completed with commit #89243f0.
